name: tweet

# Run every 4 hours throughout the day
on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
            pip3 install wheel setuptools 
            pip3 install kiwisolver 
            pip3 install matplotlib numpy tweepy
      
      - name: Run the script
        run: python3 farris_control.py
        env:
          CONSUMERKEY: ${{ secrets.CONSUMERKEY }}
          CONSUMERSECRET: ${{ secrets.CONSUMERSECRET }}
          VERIFIERTOKEN: ${{ secrets.VERIFIERTOKEN }}
          VERIFIERSECRET: ${{ secrets.VERIFIERSECRET }}
